# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtWidgets import QToolButton, QMainWindow, QApplication




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 110, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 380, 113, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        # self.pushButton_3.setCheckable(True)
        # self.pushButton_3.toggle()
        self.pushButton_3.clicked.connect(self.Clickme)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 151, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 260, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 110, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 20, 181, 16))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 110, 111, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 410, 341, 16))
        self.label_10.setObjectName("label_10")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(410, 110, 111, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 300, 101, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(520, 300, 113, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(410, 300, 101, 16))
        self.label_9.setObjectName("label_9")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 70, 161, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 330, 113, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 260, 131, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(520, 260, 113, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 330, 101, 16))
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 190, 101, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 300, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(410, 260, 101, 16))
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Browse File"))
        self.pushButton_3.setText(_translate("MainWindow", "Process Data"))
        self.label_2.setText(_translate("MainWindow", "Pre-compression Matrix"))
        self.pushButton.setText(_translate("MainWindow", "Browse File"))
        self.label.setText(_translate("MainWindow", "Coupled Filtering Algorithm"))
        self.label_10.setText(_translate("MainWindow", "Note: Matrix T refers to ..... while Matrix M refers to......"))
        self.label_6.setText(_translate("MainWindow", "Matrix T Range:"))
        self.label_9.setText(_translate("MainWindow", "Matrix M Step:"))
        self.label_3.setText(_translate("MainWindow", "Post-compression Matrix"))
        self.label_5.setText(_translate("MainWindow", "Number of Windows:"))
        self.label_8.setText(_translate("MainWindow", "Matrix T Step:"))
        self.label_4.setText(_translate("MainWindow", "Input Variables"))
        self.label_7.setText(_translate("MainWindow", "Matrix M Range:"))
        
    def Clickme(self):
        print("Button Pressed")
        # d = QDialog()
        # b1 = QPushButton("ok",d)
        # b1.move(50,50)
        # d.setWindowTitle("Dialog")
        # d.setWindowModality(Qt.ApplicationModal)
        # d.exec_()

        # app = QtWidgets.QApplication(sys.argv)
        # SecDialog = QtWidgets.QDialog()
        # ui = Ui_SecDialog()
        # ui.setupUi(SecDialog)
        # SecDialog.show()
        # sys.exit(app.exec_())
        SecDialog = QtWidgets.QDialog()
        ui = Ui_SecDialog()
        ui.setupUi(SecDialog)
        SecDialog.show()
        SecDialog.setModal(True)
        SecDialog.exec()

class Ui_SecDialog(object):
    def setupUi(self, SecDialog):
        SecDialog.setObjectName("SecDialog")
        SecDialog.resize(660, 449)
        self.textBrowser = QtWidgets.QTextBrowser(SecDialog)
        self.textBrowser.setGeometry(QtCore.QRect(280, 130, 101, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(SecDialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(280, 180, 101, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_4 = QtWidgets.QLabel(SecDialog)
        self.label_4.setGeometry(QtCore.QRect(40, 180, 211, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(SecDialog)
        self.label_5.setGeometry(QtCore.QRect(40, 230, 191, 16))
        self.label_5.setObjectName("label_5")
        self.textBrowser_3 = QtWidgets.QTextBrowser(SecDialog)
        self.textBrowser_3.setGeometry(QtCore.QRect(280, 230, 101, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        # self.pushButton = QtWidgets.QPushButton(SecDialog)
        # self.pushButton.setGeometry(QtCore.QRect(20, 340, 151, 32))
        # self.pushButton.setObjectName("pushButton")
        # self.pushButton.clicked.connect(self.Clickme_MainPage)
        self.pushButton_2 = QtWidgets.QPushButton(SecDialog)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 340, 171, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(SecDialog)
        self.label_2.setGeometry(QtCore.QRect(280, 90, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(SecDialog)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 211, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(SecDialog)
        self.label.setGeometry(QtCore.QRect(330, 40, 41, 16))
        self.label.setObjectName("label")

        self.retranslateUi(SecDialog)
        QtCore.QMetaObject.connectSlotsByName(SecDialog)

    # def Clickme_MainPage(self):
    #     print("Button Pressed")
    #     SecDialog = QtWidgets.QDialog()
    #     SecDialog.close()
    #     SecDialog.hide()


    def retranslateUi(self, SecDialog):
        _translate = QtCore.QCoreApplication.translate
        SecDialog.setWindowTitle(_translate("SecDialog", "Dialog"))
        self.label_4.setText(_translate("SecDialog", "After Affine Warping Procedure:"))
        self.label_5.setText(_translate("SecDialog", "After Coupled Filtering Method:"))
        # self.pushButton.setText(_translate("SecDialog", "Return to Main page"))
        self.pushButton_2.setText(_translate("SecDialog", "Output B-mode images"))
        self.label_2.setText(_translate("SecDialog", "Correlation Coefficient"))
        self.label_3.setText(_translate("SecDialog", "Before Affine Warping Procedure:"))
        self.label.setText(_translate("SecDialog", "Result"))
        
def main():
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    
if __name__ == "__main__":
    main()


